# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog.

# Site settings
title: "Jekyll Actions Demo"
email: m.naslcheraghi@gmail.com
description: >- 
  Explore the latest research and insights in space science, from quantum mechanics to cosmic discoveries.

baseurl: "/mansnc.github.io" # the subpath of your site
url: "https://mansnc.github.io" # the base hostname & protocol for your site
twitter_username: m_naslcheraghi
github_username: mansnc

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Allow Bundler cache for faster builds
bundler-cache: false
