name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Necessary for writing contents to the repository
      id-token: write  # Allows the action to fetch ID token

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Ruby 3.x
    - name: Set up Ruby 3.x
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    # Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    # Build Jekyll site
    - name: Build Jekyll site
      run: bundle exec jekyll build

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages
        timeout: 600000
        error_count: 10
        reporting_interval: 5000
        preview: false
