name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'  # specify the Ruby version you want to use
    
    # Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    
    # Build the site with Jekyll
    - name: Build the site with Jekyll
      run: |
        jekyll build

    # List files in _site to verify the build
    - name: List files in _site
      run: ls -alh _site

    # Upload the build artifact
    - name: Upload artifact for GitHub Pages deployment
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: _site/

    # Deploy to GitHub Pages using the artifact
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages
