name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Ensures the GitHub token has write permissions for the repository content
      id-token: write   # Grants permission to issue an OIDC token

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site with Jekyll
      run: |
        jekyll build

    - name: List files in _site
      run: ls -alh _site

    - name: Upload artifact for GitHub Pages deployment
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: _site/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages
